spring:
  jpa:
    generate-ddl: "true"
    open-in-view: "false"
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
  datasource:
    url:
    password:
    username:
  task:
    scheduling:
      pool:
        size: 4
