spring:
  jpa:
    generate-ddl: on
    open-in-view: off
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL10Dialect"
  datasource:
    url:
    username:
    password:
  quartz:
    overwriteExistingJobs: on
    properties:
      org.quartz.scheduler.instanceName: "insidebot-quartz"
      org.quartz.scheduler.instanceId: "AUTO"
      org.quartz.threadPool.threadCount: "2"
      org.quartz.jobStore.class: "org.quartz.impl.jdbcjobstore.JobStoreTX"
      org.quartz.jobStore.driverDelegateClass: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
      org.quartz.jobStore.useProperties: "true"
      org.quartz.jobStore.misfireThreshold: "60000"
      org.quartz.jobStore.tablePrefix: "qrtz_"
      org.quartz.jobStore.isClustered: "false"
      org.quartz.jobStore.clusterCheckinInterval: "20000"
  task:
    scheduling:
      pool:
        size: 4
      thread-name-prefix: "inside-scheduler-"

insidebot:
  token:
